### ISSUE TITLE
Error: Could not find module 'Jumio' for target 'arm64-apple-ios-simulator'

### ISSUE THREAD

**Issue by ptfly** [Jumio/mobile-react#43]
Hi, can someone help, will be much appreciated:
```
JumioCustomization.swift:1:8: error: could not find module 'Jumio' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64(url)
```
Part of my Podfile:
```

  post_install do |installer|

    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end

    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
  end
```

**Comment by ogjurgjej** [comment]
hi @ptfly the current iOS SDK and plugin do not support arm64 for simulator slice.
https://github.com/jumio/mobile-sdk-ios#general-requirements

**Comment by ptfly** [comment]
I saw that but how I can work with v3.9.2 and not with the latest version? Is there any workaround? That's a massive problem for us right now!

**Comment by ogjurgjej** [comment]
this issue only affects simulator builds. You will still be able to run on device and build for release.

for further questions please contact Jumio support --> https://github.com/Jumio/mobile-react#contact
